### ISSUE TITLE
Viserver not working

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyABC#19]
Running the visualization server via `abc-server /tmp/test.db` fails instantly (up-to-date master branch).

Error message:

Traceback (most recent call last):
  File "/home/yannik/anaconda3/bin/abc-server", line 11, in <module>
    load_entry_point('pyabc==0.8.20', 'console_scripts', 'abc-server')()
  File "/home/yannik/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/yannik/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/home/yannik/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/home/yannik/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/yannik/anaconda3/lib/python3.6/site-packages/pyabc/visserver/server.py", line 19, in <module>
    from bkcharts import Line  # noqa: E402
  File "/home/yannik/anaconda3/lib/python3.6/site-packages/bkcharts/__init__.py", line 17, in <module>
    from .builders.histogram_builder import Histogram
  File "/home/yannik/anaconda3/lib/python3.6/site-packages/bkcharts/builders/histogram_builder.py", line 27, in <module>
    from .bar_builder import BarBuilder
  File "/home/yannik/anaconda3/lib/python3.6/site-packages/bkcharts/builders/bar_builder.py", line 21, in <module>
    from bokeh.core.enums import Aggregation
ImportError: cannot import name 'Aggregation'

**Comment by neuralyzer** [comment]
I've been having repeatedly trouble with API breaking releases of bokeh. This seems to be related to the deprecation of the bkcharts module which is now its own package. In the long rung I'm really wondering whether we should consider an alternative to bokeh.
