### ISSUE TITLE
Error running Parameter inference example - 'ValueError: Cell is empty'

### ISSUE THREAD

**Issue by JeremySMorgan** [ICB-DCM/pyABC#356]
When I run the `Parameter inference` example  I get the following error:

```
INFO:Sampler:Parallelizing the sampling on 8 cores.
INFO:History:Start <ABCSMC(id=4, start_time=2020-10-24 16:25:42.638359, end_time=None)>
INFO:ABC:Calibration sample before t=0.
Traceback (most recent call last):
  File "/Users/admin/Documents/Duke/Academics/Senior Year/Ind Study- Ames/software/nnik_conditional/src/abc_calc.py", line 47, in <module>
    abc_calc.example()
  File "/Users/admin/Documents/Duke/Academics/Senior Year/Ind Study- Ames/software/nnik_conditional/src/abc_calc.py", line 39, in example
    history = abc.run(minimum_epsilon=.1, max_nr_populations=10)
  File "/Users/admin/Documents/Duke/Academics/Senior Year/Ind Study- Ames/software/nnik_conditional/venv/lib/python3.6/site-packages/pyabc/inference/smc.py", line 606, in run
    self._initialize_dist_eps_acc(t0)
  File "/Users/admin/Documents/Duke/Academics/Senior Year/Ind Study- Ames/software/nnik_conditional/venv/lib/python3.6/site-packages/pyabc/inference/smc.py", line 431, in _initialize_dist_eps_acc
    self.acceptor.get_epsilon_config(t))
  File "/Users/admin/Documents/Duke/Academics/Senior Year/Ind Study- Ames/software/nnik_conditional/venv/lib/python3.6/site-packages/pyabc/epsilon/epsilon.py", line 149, in initialize
    weighted_distances = get_weighted_distances()
  File "/Users/admin/Documents/Duke/Academics/Senior Year/Ind Study- Ames/software/nnik_conditional/venv/lib/python3.6/site-packages/pyabc/inference/smc.py", line 403, in get_initial_weighted_distances
    population = _get_initial_population_with_distances()
  File "/Users/admin/Documents/Duke/Academics/Senior Year/Ind Study- Ames/software/nnik_conditional/venv/lib/python3.6/site-packages/pyabc/inference/smc.py", line 394, in _get_initial_population_with_distances
    population = self._get_initial_population(t)
  File "/Users/admin/Documents/Duke/Academics/Senior Year/Ind Study- Ames/software/nnik_conditional/venv/lib/python3.6/site-packages/pyabc/inference/smc.py", line 452, in _get_initial_population
    population = self._sample_from_prior(t)
  File "/Users/admin/Documents/Duke/Academics/Senior Year/Ind Study- Ames/software/nnik_conditional/venv/lib/python3.6/site-packages/pyabc/inference/smc.py", line 484, in _sample_from_prior
    max_eval=np.inf, all_accepted=True)
  File "/Users/admin/Documents/Duke/Academics/Senior Year/Ind Study- Ames/software/nnik_conditional/venv/lib/python3.6/site-packages/pyabc/sampler/base.py", line 151, in sample_until_n_accepted
    sample = f(self, n, simulate_one, max_eval, all_accepted)
  File "/Users/admin/Documents/Duke/Academics/Senior Year/Ind Study- Ames/software/nnik_conditional/venv/lib/python3.6/site-packages/pyabc/sampler/multicore_evaluation_parallel.py", line 104, in sample_until_n_accepted
    simulate_one = pickle.dumps(simulate_one)
  File "/Users/admin/Documents/Duke/Academics/Senior Year/Ind Study- Ames/software/nnik_conditional/venv/lib/python3.6/site-packages/cloudpickle/cloudpickle_fast.py", line 102, in dumps
    cp.dump(obj)
  File "/Users/admin/Documents/Duke/Academics/Senior Year/Ind Study- Ames/software/nnik_conditional/venv/lib/python3.6/site-packages/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/admin/Documents/Duke/Academics/Senior Year/Ind Study- Ames/software/nnik_conditional/venv/lib/python3.6/site-packages/cloudpickle/cloudpickle_fast.py", line 745, in save_function
    *self._dynamic_function_reduce(obj), obj=obj
  File "/Users/admin/Documents/Duke/Academics/Senior Year/Ind Study- Ames/software/nnik_conditional/venv/lib/python3.6/site-packages/cloudpickle/cloudpickle_fast.py", line 682, in _save_reduce_pickle5
    dictitems=dictitems, obj=obj
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/admin/Documents/Duke/Academics/Senior Year/Ind Study- Ames/software/nnik_conditional/venv/lib/python3.6/site-packages/dill/_dill.py", line 1169, in save_cell
    f = obj.cell_contents
ValueError: Cell is empty
```

What's going on here? Is there someway to fix this issue? Thanks.

Running 0.10.7 on my Mac

Here's my code:
	```
import scipy.stats as st
import tempfile
import os
import pandas as pd
import matplotlib.pyplot as plt

	def model(parameter):
			return {"data": parameter["mean"] + 0.5 * np.random.randn()}

		prior = pyabc.Distribution(mean=pyabc.RV("uniform", 0, 5))

		def distance(x, y):
			return abs(x["data"] - y["data"])

		abc = pyabc.ABCSMC(model, prior, distance)

		db_path = ("sqlite:///" + os.path.join(tempfile.gettempdir(), "test.db"))
		observation = 2.5
		abc.new(db_path, {"data": observation})

		history = abc.run(minimum_epsilon=.1, max_nr_populations=10)
```

**Comment by yannikschaelte** [comment]
Hi @JeremySMorgan , it looks like the pickling module on MacOS is again not doing what it is supposed to do. It should be possible to "fix" this by using `abc = pyabc.ABCSMC(..., sampler=pyabc.sampler.SingleCoreSampler())`, at the cost of single core execution as opposed to parallelization across the cores of your notebook.

To have parallelization, can you try using `sampler=pyabc.sampler.MulticoreEvalParallelSampler(pickle=True/False)`? Is is supposed to automatically detect MacOS, but apparently on some systems this does not work yet properly.

**Comment by EmadAlamoudi** [comment]
Dear @JeremySMorgan , I would like to add one additional suggestion to what already mentioned by Yannik. Which version of `cloudpickle` package you are using? I had similar issues when using cloudpickle=`1.5.0` or `1.5.1` or `1.6.0`. If that is the case, try to downgrade it to `cloudpickle==1.4.1` that might fix the issue.

**Comment by yannikschaelte** [comment]
Hi @JeremySMorgan , closing due to inactivity. Please feel free to re-open if the issue persists!
