### ISSUE TITLE
Error when using LocalTransition

### ISSUE THREAD

**Issue by frank-pieterse** [ICB-DCM/pyABC#394]
Hi,

I wanted to use the local transition kernel in my abc-smc script. When using this kernel I came across some errors. Note that the algorithm runs fine when i use the MultivariateNormal transition kernel.
The error originates from this:
```
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
```
Here, the cov_distance is the issue. If i print it, it for example is:
[ 3.30216349e+03 -2.04358241e+16 -7.75000000e+00 -2.89750745e+16]
They are extremely big, which then is an issue if you take the exponent.

Some runs, i get the warning:
WARNING:pyabc.inference.util:Unusually many (model, parameter) samples have prior density zero. The transition might be inappropriate.

Does this mean i cannot use the local transition kernel? Or is there some way to fix this?
Thanks in advance!

The script i use i will add below.
It uses model files and a distance function from another file i made (model_files). There is data in there that i am unable to share, so i will not add that script. The model functions output a dict, and the distance function outputs the log(SSR). I'm using time series data for this.
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    Script that runs ABC-SMC on my machine for testing. Uses the solver and
    distance function from model_files.py

    Functions
    ----------
    main
    function that calls run_abc to run the abc-smc algorithm
    Can be adapted to run it multiple times.

    run_abc
    function that creates a new abc-smc run.

    returns a vector of right-hand sides of odes in the same order as y.

    ----------
    """
import pyabc
import os
import numpy as np

# import model_files (from other python file in the same dir)
import model_files


def main():
    """
    main loop that calls the run_abc function
    Returns
    -------

    """
    # load in data
    measured_data = model_files.import_data_dki_avg(
        csv_file="rescaled_dki_data.csv"
    )
    # set path to the database (in current working directory)
    db_name = "/test_run.db"
    database_path = ("sqlite:///" + os.path.abspath(os.getcwd())+db_name)
    epsilon = pyabc.epsilon.QuantileEpsilon(alpha=0.3)
    trans = pyabc.transition.LocalTransition(k_fraction=0.99)
    # use abc function from this script to run the algorithm
    for i in range(10):
        run_abc(database_path, measured_data, epsilon, trans)

    # results can be visualized here, or the history can be loaded into another
    # script. The latter is preferred, to save time (not having to run each
    # time is nice)


def run_abc(db_path, data, epsilon_input, transition_input):
    """
    runs the abc-smc algorithm, gives the output as a history object.

    Parameters
    ----------
    db_path: str
        name of the path for the database.db file
    data: dict
        output of the import_data_dki function
    epsilon_input: pyabc.Epsilon object
        epsilon scheme to be used.
    transition_input: pyabc.Transition object
        transition kernel to be used.

    Returns
    -------
    history:pyabc.History object
        object that connects to the database file containing the output
    """
    # load in models from model_files
    models = [model_files.fun_00,
              model_files.fun_01,
              model_files.fun_02,
              model_files.fun_10,
              model_files.fun_11,
              model_files.fun_12,
              model_files.fun_20,
              model_files.fun_21,
              model_files.fun_22,
              ]

    # define priors
    priors = [pyabc.Distribution(k_dim_n=pyabc.RV("uniform", 1.5, 3.5),
                                 k_mon=pyabc.RV("uniform", -1, 2),
                                 k_in=pyabc.RV("uniform", 0, 3),
                                 k_out=pyabc.RV("uniform", 0, 2),
                                 k_prod_arf1=pyabc.RV("uniform", -0.5, 1.5),
                                 k_prod_arf2=pyabc.RV("uniform", -0.5, 1.5),
                                 k_d_arf1_n=pyabc.RV("uniform", -1.5, 0.5),
                                 k_d_arf2_n=pyabc.RV("uniform", -1.5, 0.5),
                                 k_d_arf1_arf1_n=pyabc.RV("uniform", -1.5, 0.5),
                                 k_d_arf1_arf2_n=pyabc.RV("uniform", -1.5, 0.5),
                                 k_d_arf2_arf2_n=pyabc.RV("uniform", -1.5, 0.5),
                                 arf1_0=pyabc.RV("uniform", 0, 2.5),
                                 arf2_0=pyabc.RV("norm", np.log10(30),
                                                 np.log10(10)))
              for _ in models]

    # call main ABC function
    abc = pyabc.ABCSMC(
        models=models,
        parameter_priors=priors,
        distance_function=model_files.distance_function,
        sampler=pyabc.sampler.SingleCoreSampler(),
        transitions=[transition_input for _ in range(len(models))],
        eps=epsilon_input,
        population_size=100)

    # make new abc-smc run
    abc.new(db_path, data)

    # run the abc-smc algorithm
    h = abc.run(max_nr_populations=5)
    return h


if __name__ == "__main__":
    main()

```

The full error traceback is:

```
C:\Users\frank\anaconda3\python.exe "E:/_Master thesis/Scripts/Pycharm_project/github_post_local_transition/main_test.py"
INFO:History:Start <ABCSMC(id=3, start_time=2021-01-04 13:25:06.801939, end_time=None)>
INFO:ABC:Calibration sample before t=0.
INFO:Epsilon:initial epsilon is 11.549010700901338
INFO:ABC:t: 0, eps: 11.549010700901338.
INFO:ABC:Acceptance rate: 100 / 296 = 3.3784e-01, ESS=1.0000e+02.
INFO:ABC:t: 1, eps: 9.81743737070117.
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:109: RuntimeWarning: overflow encountered in exp
  return np.average(np.exp(-.5 * cov_distance) / self.normalization,
C:\Users\frank\anaconda3\lib\site-packages\pyabc\population.py:145: RuntimeWarning: invalid value encountered in double_scalars
  particle.weight /= model_total_weight
INFO:ABC:Acceptance rate: 100 / 220 = 4.5455e-01, ESS=nan.
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\util.py:14: RuntimeWarning: Degrees of freedom <= 0 for slice
  cov = np.cov(X_arr, aweights=w, rowvar=False)
C:\Users\frank\anaconda3\lib\site-packages\numpy\lib\function_base.py:2480: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)
C:\Users\frank\anaconda3\lib\site-packages\numpy\lib\function_base.py:2480: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
C:\Users\frank\anaconda3\lib\site-packages\numpy\linalg\linalg.py:2159: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)
C:\Users\frank\anaconda3\lib\site-packages\pyabc\transition\local_transition.py:135: RuntimeWarning: invalid value encountered in true_divide
  local_weights / local_weights.sum())
Traceback (most recent call last):
  File "E:/_Master thesis/Scripts/Pycharm_project/github_post_local_transition/main_test.py", line 121, in <module>
    main()
  File "E:/_Master thesis/Scripts/Pycharm_project/github_post_local_transition/main_test.py", line 46, in main
    run_abc(database_path, measured_data, epsilon, trans)
  File "E:/_Master thesis/Scripts/Pycharm_project/github_post_local_transition/main_test.py", line 116, in run_abc
    h = abc.run(max_nr_populations=5)
  File "C:\Users\frank\anaconda3\lib\site-packages\pyabc\inference\smc.py", line 665, in run
    self._prepare_next_iteration(
  File "C:\Users\frank\anaconda3\lib\site-packages\pyabc\inference\smc.py", line 718, in _prepare_next_iteration
    self._fit_transitions(t)
  File "C:\Users\frank\anaconda3\lib\site-packages\pyabc\inference\smc.py", line 816, in _fit_transitions
    particles, w = self.history.get_distribution(m, t - 1)
  File "C:\Users\frank\anaconda3\lib\site-packages\pyabc\storage\history.py", line 28, in f_wrapper
    res = f(self, *args, **kwargs)
  File "C:\Users\frank\anaconda3\lib\site-packages\pyabc\storage\history.py", line 308, in get_distribution
    if w_arr.size > 0 and not np.isclose(w_arr.sum(), 1):
  File "<__array_function__ internals>", line 5, in isclose
  File "C:\Users\frank\anaconda3\lib\site-packages\numpy\core\numeric.py", line 2287, in isclose
    xfin = isfinite(x)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

Process finished with exit code 1

```

**Comment by yannikschaelte** [comment]
Hi @frank-pieterse , apologies, we somehow did not get this issue. Is it still a thing? The first problem you describe (many evaluations of density zero) typically occurs if one uses a discrete prior, which seems not to be the case. It can also occur if optimal parameters lie on the boundary of the prior domain, such that the transition kernel proposes many particles outside it.

Regarding the second issue: In the meantime, the transitions have been significantly reworked. Could you confirm that the issue remains with the latest version of pyabc?

**Comment by ljschumacher** [comment]
I still get the warning "Unusually many (model, parameter) samples have prior density zero. The transition might be inappropriate" in the latest version, when using log-uniform priors. What do you suggest for evaluating whether this warning can be ignored or not? (e.g. changing prior bounds, number of particles, looking for posterior density near boundaries)

**Comment by yannikschaelte** [comment]
The number of particles should have next-to-no influence (if it's high enough). As everything is continuous, I would guess that the optimal parameters are very on the boundary, i.e. in this case 0, the bound of support of the log-uniform distribution. It may help to plot prior vs the posterior approximations over the iterations (I hope there are any iterations that finish?). The latter can be obtained via pyabc.visualization.plot_kde_1d, as in https://pyabc.readthedocs.io/en/latest/examples/parameter_inference.html.

The problem only occurs for the LocalTransition? Then there may by chance something go wrong there. We are usually happy with the simple MultivariateNormal transition.

**Comment by ljschumacher** [comment]
Well, since it's log-uniform the support will not reach 0, but 10^-a. If this means some parameters are likely 0 I'm happy to ignore this, but I'll have to look at the posteriors. I'm attaching the suggested plot for one (of 14) parameters, which doesn't look like it's getting closer to the boundaries.
[top_model_chir_coupled_test_posti_iterations.pdf](https://github.com/ICB-DCM/pyABC/files/6183982/top_model_chir_coupled_test_posti_iterations.pdf)


There are plenty of iterations that finish (at least 10 generations – is that what you mean by iteration?), and the epsilons look like they're decreasing ok.

I've previously found the LocalTransition kernel to give me faster convergence for this problem, but I'll check again with the MultivariateNormal.

**Comment by yannikschaelte** [comment]
The posteriors look good, the data seem to push towards higher values. I can't see why so many 0-prior points should occur tbd, weird. For the LocalTransition I would recommend a lower k_fraction, e.g.  0.2 - 0.6. For production runs (the final analyses), a population size of >>100 may be good, depending on the evaluation cost and infrastructure.

**Comment by ljschumacher** [comment]
This was 10k particles and k-fraction 0.25. More than 100 iterations/generations (if that's what you meant) is infeasible, but I don't see how that should affect this warning we're getting. 

I've attached the plot for all parameters. The last one is much lower, but again it doesn't look like it's getting closer to 0 with later iterations.
[top_model_chir_uncoupled_test_posti_iterations.pdf](https://github.com/ICB-DCM/pyABC/files/6188258/top_model_chir_uncoupled_test_posti_iterations.pdf)

**Comment by yannikschaelte** [comment]
Ah, ok. I meant by "population size" the size of each population, which you specify via `ABCSMC(..., population_size=1000)`. Regarding iterations/generations: There we usually observe something between 8 and 40 to be feasible.

One comment: Many of your posteriors seem to be suggesting larger values, overruling the prior. Maybe softening the prior / making it more uninformative might help if that is possible?

**Comment by ljschumacher** [comment]
So we are now thinking that the issue might be that our prior is uniform in log-space but the KDE for the transition is in linear space. We're thinking we could write a version of the local transition kernel where we simply transform self.X_arr to logspace, and exponentiate the samples before returning by rvs_single. Do you think that's sound?

**Comment by yannikschaelte** [comment]
Hi @ljschumacher , sorry for having missed this. Yes, totally agreed that scale transformations may have an effect. Note that pyABC "does not know" anything about scales, so when your prior is on log-scale, then also the transition kernel will be on log-scale.

**Comment by ljschumacher** [comment]
for clarification: I was saying that currently even when the prior is on log-scale, the (local) transition kernel as currently implemented will be on a linear scale – are you saying this is not so? What I mean by this is that the "step-size" around the current sample will be equally weighted left or right (on the linear scale), whereas in my understanding for a log-prior this ought to take place in the log-space of parameters. Am I making any sense?

I was proposing of implementing myself (which I have done) a transformation to log-scale within the local transition kernel (as a new custom kernel).

**Comment by yannikschaelte** [comment]
I am not sure whether I fully get the point. If your new implementation works better, then there certainly was a point ;)

What I meant: Say you have a uniform prior on log-space, then you will get evenly sampled values `\theta \sim [\log a, \log b]` under the prior. In your model, you then probably transform those values to `\gamma = exp(\theta)` and use gamma in your model. However, pyABC does not know that gamma (or a lin-space) exists, it operates only on the log-space, and therefore also defines its transition kernels as symmetric Normal distributions in that (log-)space, i.e. everything in terms of theta.

One potential problem could be if in your code you operate directly on the input variables,

```python
def model(p)
    for key in p:
        p[key] = np.exp(p[key])
        # model simulation ...
```
as in this case you change the actual value of p, which pyABC will then later work with after the model simulation. instead, values should be changed only on a copy of the object, `p = copy.deepcopy(p)`, to work with for model simulation.

**Comment by ljschumacher** [comment]
I think I see the source of the confusion. In my model I was not exponentiating the parameters with a uniform prior. Instead, I was specifying log-uniform distributions as the priors directly. The reason being that we needed to switch between uniform and log-uniform priors in prototyping. 

So in our case the transitions were doing a Normal distribution in linear space, not log-space. So we tried taking a log of the parameters before the normal distribution is estimated, and exponentiating again before return the new parameter samples.

Of course the way you describe would also work and allow us to use the built-in transitions, so that may be easier - and perhaps faster.

**Comment by yannikschaelte** [comment]
Ah, thanks for the clarification. In that case I totally agree that an asymmetric e.g. log-normal transition kernel may be of advantage.

Note that indeed from a Bayesian point of view the space on which the prior is defined (which in my case would be the log-space, in yours the lin-space) is part of the problem formulation. Applying a transformation can e.g. shift the MAP estimate, so they are not equivalent. Thus, I assume that what you did was the right thing in your application.

(Note: In your transition, it may be necessary to apply transformation derivatives of the log-transform for pdf calculation, in order to have a correct density in lin-space.)
