### ISSUE TITLE
Using `tfp.distributions`  and implement in `pyabc.Distribution`

### ISSUE THREAD

**Issue by mehradans92** [ICB-DCM/pyABC#471]
Hi. Is there a way to use parameter distributions that come from `tfp.distributions` and use them in pyABC while calling `pyabc.Distribution`?

**Comment by yannikschaelte** [comment]
Hi, in general a distribution can be any non-normalized probability distribution implementing methods `rvs()` to sample and `pdf()` to evaluate particle densities, see https://github.com/ICB-DCM/pyABC/blob/main/pyabc/random_variables.py#L303. Thus, tfp should be possible. Only for parallelization care may need to be taken w.r.t. pseudo random number generator initialization.

**Comment by mehradans92** [comment]
Thanks for your reply. I am not sure how it can be implemented tho.  `tfp.distributions` are generated using `sample` after they have defined. Does that need to be set in `pyabc.Distribution`? By any chance do you have a working example that you can share?

**Comment by yannikschaelte** [comment]
Tbh I never worked with tfp (you mean classes such as https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/Uniform ?), so no working example, but what I would go for is a derived class via a Wrapper pattern. Very roughly, it would look like

```python
class TfpDistribution(pyabc.Distribution):

    def __init__(self, tfp_distribution: tfp.Distribution):
        # initialize from arguments, or e.g. just pass a tfp distribution object and save it as an attribute
        self.tfp_distribution = tfp_distribution

    def rvs(self):
        return self.tfp_distribution.sample()

    def pdf(self, x):
        return self.tfp_distribution.prob(x)
```

Is that what you mean?

**Comment by mehradans92** [comment]
Yup. Thanks. I figured out the code but it only seems to be working for `max_nr_populations=1`. 
```
import tensorflow_probability as tfp
tfd = tfp.distributions

class TfpDistribution(pyabc.RV):

    def __init__(self, tfp_distribution):
        # initialize from arguments, or e.g. just pass a tfp distribution object and save it as an attribute
        self.tfp_distribution = tfp_distribution

    def rvs(self):
        return self.tfp_distribution.sample()

    def pdf(self, x):
        return self.tfp_distribution.prob(x)

beta_A_low = 0.005
beta_A_high = 0.08
abc_param_locs = [0.01, 0.01, 2, 2, 6, 6]
abc_param_stds = [0.1, 0.1, 0.5, 0.5, 2, 2]
trunc_norm = tfp.distributions.TruncatedNormal(
    low=beta_A_low, scale=abc_param_stds[0], loc=abc_param_locs[0], high=beta_A_high, name='trunc_norm')

parameter_priors = pyabc.Distribution(beta_A = TfpDistribution(trunc_norm),
                                      beta_I = pyabc.RV('truncnorm', a=(abc_param_locs[1]-beta_A_low)/abc_param_stds[1], loc=abc_param_locs[1], scale=abc_param_stds[1],b=(beta_A_high - abc_param_locs[1])/abc_param_stds[1]),
                                      E_A_time=pyabc.RV('norm', abc_param_locs[2], abc_param_stds[2]),
                                      E_I_time=pyabc.RV('norm', abc_param_locs[3], abc_param_stds[3]),
                                      A_R_time=pyabc.RV('norm', abc_param_locs[4], abc_param_stds[4]),
                                      I_R_time=pyabc.RV('norm', abc_param_locs[5], abc_param_stds[5]))

def distance(x, y):
    d = np.sum(np.abs(np.log(x['data']) - np.log(y['data'])))
    return d

abc = pyabc.ABCSMC(abc_model, parameter_priors, distance, population_size=100) # population_size=1024*16
db_path = 'sqlite:///' + os.path.join(os.getcwd(), 'abc_SEAIR.db') 
abc.new(db_path, {'data': observations})

history = abc.run(minimum_epsilon=0.01, max_nr_populations=2)
df, w_abc = history.get_distribution(m=0, t=history.max_t)
```
```
INFO:ABC:Calibration sample before t=0.
INFO:Epsilon:initial epsilon is 156.18084094996877
INFO:ABC:t: 0, eps: 156.18084094996877.
INFO:ABC:Acceptance rate: 100 / 279 = 3.5842e-01, ESS=1.0000e+02.
INFO:ABC:t: 1, eps: 110.33575223743063.
Process Process-361:
Traceback (most recent call last):
Process Process-362:
  File "/home/mgholiza/.conda/envs/covid-19/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/mgholiza/.conda/envs/covid-19/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mgholiza/.local/lib/python3.7/site-packages/pyabc/sampler/multicore_evaluation_parallel.py", line 38, in work
    new_sim = simulate_one()
  File "/home/mgholiza/.local/lib/python3.7/site-packages/pyabc/inference/util.py", line 377, in simulate_one
    transitions=transitions)
  File "/home/mgholiza/.local/lib/python3.7/site-packages/pyabc/inference/util.py", line 123, in generate_valid_proposal
    theta_ss = Parameter(**transitions[m_ss].rvs().to_dict())
  File "/home/mgholiza/.local/lib/python3.7/site-packages/pyabc/transition/transitionmeta.py", line 38, in rvs
    return f(self, size)
  File "/home/mgholiza/.local/lib/python3.7/site-packages/pyabc/transition/multivariatenormal.py", line 87, in rvs
    sample_ind = np.random.choice(arr, size=size, p=self.w, replace=True)
Traceback (most recent call last):
  File "mtrand.pyx", line 924, in numpy.random.mtrand.RandomState.choice
  File "/home/mgholiza/.conda/envs/covid-19/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
Process Process-363:
ValueError: probabilities do not sum to 1
  File "/home/mgholiza/.conda/envs/covid-19/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mgholiza/.local/lib/python3.7/site-packages/pyabc/sampler/multicore_evaluation_parallel.py", line 38, in work
    new_sim = simulate_one()
  File "/home/mgholiza/.local/lib/python3.7/site-packages/pyabc/inference/util.py", line 377, in simulate_one
    transitions=transitions)
  File "/home/mgholiza/.local/lib/python3.7/site-packages/pyabc/inference/util.py", line 123, in generate_valid_proposal
    theta_ss = Parameter(**transitions[m_ss].rvs().to_dict())
  File "/home/mgholiza/.local/lib/python3.7/site-packages/pyabc/transition/transitionmeta.py", line 38, in rvs
    return f(self, size)
  File "/home/mgholiza/.local/lib/python3.7/site-packages/pyabc/transition/multivariatenormal.py", line 87, in rvs
    sample_ind = np.random.choice(arr, size=size, p=self.w, replace=True)
  File "mtrand.pyx", line 924, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities do not sum to 1
Traceback (most recent call last):
  File "/home/mgholiza/.conda/envs/covid-19/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/mgholiza/.conda/envs/covid-19/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
Process Process-364:
  File "/home/mgholiza/.local/lib/python3.7/site-packages/pyabc/sampler/multicore_evaluation_parallel.py", line 38, in work
    new_sim = simulate_one()
  File "/home/mgholiza/.local/lib/python3.7/site-packages/pyabc/inference/util.py", line 377, in simulate_one
    transitions=transitions)
  File "/home/mgholiza/.local/lib/python3.7/site-packages/pyabc/inference/util.py", line 123, in generate_valid_proposal
    theta_ss = Parameter(**transitions[m_ss].rvs().to_dict())
  File "/home/mgholiza/.local/lib/python3.7/site-packages/pyabc/transition/transitionmeta.py", line 38, in rvs
    return f(self, size)
  File "/home/mgholiza/.local/lib/python3.7/site-packages/pyabc/transition/multivariatenormal.py", line 87, in rvs
    sample_ind = np.random.choice(arr, size=size, p=self.w, replace=True)
  File "mtrand.pyx", line 924, in numpy.random.mtrand.RandomState.choice
Traceback (most recent call last):
ValueError: probabilities do not sum to 1
  File "/home/mgholiza/.conda/envs/covid-19/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
```

**Comment by yannikschaelte** [comment]
the error seems to be that the weights do not sum to 1. does it work when you use a simple scipy RV instead of the tfp? Then it would be that the density evaluation function does not yet work properly.

**Comment by mehradans92** [comment]
Yes it works with a simple scipy RV. Is there a way to redefine the density evaluation function?

**Comment by yannikschaelte** [comment]
Sorry, what exactly do you mean by that?

**Comment by mehradans92** [comment]
So you said this could be coming from the density evaluation function not yet working properly. I was wondering where to look for troubleshooting. Also, do you know if there is a way to count the number of function evaluations for `model` in pyabc? What I am looking for is to stop the iterations in pyabc based on the defined number of function evaluations rather that defining an `epsilon` or `max_nr_populations` for stopping.

**Comment by yannikschaelte** [comment]
I guess the easiest way of debugging would be to insert good old print statements in your custom rv class, of inputs and outputs :)

The [run](https://github.com/ICB-DCM/pyABC/blob/main/pyabc/inference/smc.py#L571) function knows multiple stopping criteria, max_total_nr_simulations seems like what you are looking for.

**Comment by mehradans92** [comment]
Thanks!:)
