### ISSUE TITLE
AssertionError: The total population weight is zero

### ISSUE THREAD

**Issue by Gabriel-p** [ICB-DCM/pyABC#534]
I've encountered this error

https://github.com/ICB-DCM/pyABC/blob/7efc9265aaf32014b182a67214415ee582d64e09/pyabc/population.py#L417

when sampling with a low number of particle (25). When this happens, the entire run is thrown away. Wouldn't it be better to raise a warning and break out of the run? This way the user could still make use of the last successful population.

**Comment by yannikschaelte** [comment]
Hi @Gabriel-p , sorry for the delay. This error is usually not supposed to happen. Can you share your ABC settings?

**Comment by yannikschaelte** [comment]
It indicates that each and every particle has zero weight, which should in practice not be possible.

**Comment by Gabriel-p** [comment]
I encounter this issue testing it within my [code](https://github.com/asteca/ASteCA) which is too large to sare. Here's the relevant `pyABC` part:

```
    abc = pyabc.ABCSMC(model, prior, distance, population_size=25)
    db_path = ("sqlite:///" + os.path.join(tempfile.gettempdir(), "test.db"))
    abc.new(db_path, obs_data)

    history = abc.run(
        minimum_epsilon=0.0000001, max_nr_populations=50,
        max_walltime=dt.timedelta(hours=0, minutes=5))
```

and here's the output:

```
ABC.Sampler INFO: Parallelize sampling on 4 processes.
ABC.History INFO: Start <ABCSMC id=1, start_time=2021-12-17 09:16:29>
ABC INFO: Calibration sample t = -1.
ABC INFO: t: 0, eps: 8.88804059e+02.
ABC INFO: Accepted: 25 / 60 = 4.1667e-01, ESS: 2.5000e+01.
ABC INFO: t: 1, eps: 5.68588739e+02.
ABC INFO: Accepted: 25 / 69 = 3.6232e-01, ESS: 1.2683e+01.
ABC INFO: t: 2, eps: 4.92224761e+02.
ABC INFO: Accepted: 25 / 36 = 6.9444e-01, ESS: 1.0186e+01.
ABC INFO: t: 3, eps: 4.45054573e+02.
ABC INFO: Accepted: 25 / 58 = 4.3103e-01, ESS: 4.0914e+00.
ABC INFO: t: 4, eps: 3.86888979e+02.
ABC INFO: Accepted: 25 / 91 = 2.7473e-01, ESS: 1.7420e+01.
ABC INFO: t: 5, eps: 3.61034717e+02.
ABC INFO: Accepted: 25 / 56 = 4.4643e-01, ESS: 1.2114e+01.
ABC INFO: t: 6, eps: 3.45485511e+02.
ABC INFO: Accepted: 25 / 130 = 1.9231e-01, ESS: 1.3447e+01.
ABC INFO: t: 7, eps: 3.35992283e+02.
ABC INFO: Accepted: 25 / 47 = 5.3191e-01, ESS: 2.1038e+00.
ABC INFO: t: 8, eps: 3.31366846e+02.
ABC INFO: Accepted: 25 / 42 = 5.9524e-01, ESS: 4.4767e+00.
ABC INFO: t: 9, eps: 3.20888356e+02.
ABC INFO: Accepted: 25 / 51 = 4.9020e-01, ESS: 6.4104e+00.
ABC INFO: t: 10, eps: 3.15661492e+02.
ABC INFO: Accepted: 25 / 33 = 7.5758e-01, ESS: 1.0686e+01.
ABC INFO: t: 11, eps: 3.02212880e+02.
ABC INFO: Accepted: 25 / 66 = 3.7879e-01, ESS: 8.7892e+00.
ABC INFO: t: 12, eps: 2.95528603e+02.
ABC INFO: Accepted: 25 / 111 = 2.2523e-01, ESS: 9.5588e+00.
ABC INFO: t: 13, eps: 2.92528171e+02.
ABC INFO: Accepted: 25 / 123 = 2.0325e-01, ESS: 2.4253e+00.
ABC INFO: t: 14, eps: 2.91525891e+02.
ABC INFO: Accepted: 25 / 42 = 5.9524e-01, ESS: 4.4601e+00.
ABC INFO: t: 15, eps: 2.89532754e+02.
ABC INFO: Accepted: 25 / 74 = 3.3784e-01, ESS: 8.3407e+00.
ABC INFO: t: 16, eps: 2.85519469e+02.
ABC INFO: Accepted: 25 / 93 = 2.6882e-01, ESS: 1.6675e+01.
ABC INFO: t: 17, eps: 2.83581371e+02.
ABC INFO: Accepted: 25 / 126 = 1.9841e-01, ESS: 1.1598e+01.
ABC INFO: t: 18, eps: 2.80336328e+02.
ABC INFO: Accepted: 25 / 411 = 6.0827e-02, ESS: 1.2024e+01.
ABC INFO: t: 19, eps: 2.78980697e+02.
ABC INFO: Accepted: 25 / 449 = 5.5679e-02, ESS: 5.0757e+00.
ABC INFO: t: 20, eps: 2.75766221e+02.
ABC INFO: Accepted: 25 / 2342 = 1.0675e-02, ESS: 3.6079e+00.
ABC INFO: t: 21, eps: 2.73383965e+02.
ABC INFO: Accepted: 25 / 1361 = 1.8369e-02, ESS: 1.0899e+01.
ABC INFO: t: 22, eps: 2.71293384e+02.
ABC INFO: Accepted: 25 / 796 = 3.1407e-02, ESS: 1.0457e+01.
ABC INFO: t: 23, eps: 2.70159629e+02.
ABC INFO: Accepted: 25 / 162 = 1.5432e-01, ESS: 7.6298e+00.
ABC INFO: t: 24, eps: 2.68126542e+02.
ABC INFO: Accepted: 25 / 251 = 9.9602e-02, ESS: 2.2835e+01.
ABC INFO: t: 25, eps: 2.67289423e+02.
ABC INFO: Accepted: 25 / 244 = 1.0246e-01, ESS: 1.8133e+01.
ABC INFO: t: 26, eps: 2.66626402e+02.
ABC INFO: Accepted: 25 / 316 = 7.9114e-02, ESS: 1.0293e+00.
ABC INFO: t: 27, eps: 2.65689119e+02.
ABC INFO: Accepted: 25 / 906 = 2.7594e-02, ESS: 9.3036e+00.
ABC INFO: t: 28, eps: 2.65309641e+02.
ABC INFO: Accepted: 25 / 805 = 3.1056e-02, ESS: 1.8273e+01.
ABC INFO: t: 29, eps: 2.64841620e+02.
ABC INFO: Accepted: 25 / 563 = 4.4405e-02, ESS: 1.7813e+01.
ABC INFO: t: 30, eps: 2.64409554e+02.
ABC INFO: Accepted: 25 / 242 = 1.0331e-01, ESS: 8.8930e+00.
ABC INFO: t: 31, eps: 2.63623900e+02.
ABC INFO: Accepted: 25 / 1128 = 2.2163e-02, ESS: 1.4886e+01.
ABC INFO: t: 32, eps: 2.63403238e+02.
ABC INFO: Accepted: 25 / 1476 = 1.6938e-02, ESS: 1.8208e+01.
ABC INFO: t: 33, eps: 2.63153876e+02.
ABC INFO: Accepted: 25 / 654 = 3.8226e-02, ESS: 1.5379e+01.
ABC INFO: t: 34, eps: 2.62921046e+02.
ABC INFO: Accepted: 25 / 915 = 2.7322e-02, ESS: 2.1931e+01.
ABC INFO: t: 35, eps: 2.62472207e+02.
ABC INFO: Accepted: 25 / 728 = 3.4341e-02, ESS: 2.3615e+01.
ABC INFO: t: 36, eps: 2.61708751e+02.
ABC INFO: Accepted: 25 / 418 = 5.9809e-02, ESS: 9.3744e+00.
ABC INFO: t: 37, eps: 2.61632677e+02.
ABC INFO: Accepted: 25 / 356 = 7.0225e-02, ESS: 4.1540e+00.
ABC INFO: t: 38, eps: 2.61626027e+02.
ABC INFO: Accepted: 25 / 222 = 1.1261e-01, ESS: 1.0911e+01.
ABC INFO: t: 39, eps: 2.61581229e+02.
ABC INFO: Accepted: 25 / 126 = 1.9841e-01, ESS: 3.4150e+00.
ABC INFO: t: 40, eps: 2.61471874e+02.
ABC INFO: Accepted: 25 / 251 = 9.9602e-02, ESS: 1.9079e+01.
ABC INFO: t: 41, eps: 2.61454685e+02.
ABC INFO: Accepted: 25 / 232 = 1.0776e-01, ESS: 1.6200e+01.
ABC INFO: t: 42, eps: 2.61341069e+02.
ABC INFO: Accepted: 25 / 190 = 1.3158e-01, ESS: 2.0903e+01.
ABC INFO: t: 43, eps: 2.61194613e+02.
ABC INFO: Accepted: 25 / 83 = 3.0120e-01, ESS: 2.1528e+01.
ABC INFO: t: 44, eps: 2.61194613e+02.
ABC INFO: Accepted: 25 / 50 = 5.0000e-01, ESS: 2.0801e+01.
ABC INFO: t: 45, eps: 2.61194613e+02.
ABC.History INFO: Done <ABCSMC id=1, duration=0:01:13.649568, end_time=2021-12-17 09:17:42>

Traceback (most recent call last):
  File "/home/gabriel/Github/asteca-project/ASteCA/packages/asteca_run.py", line 65, in main
    func_caller.main(cl_file, pd)
  File "/home/gabriel/Github/asteca-project/ASteCA/packages/func_caller.py", line 306, in main
    clp = best_fit_synth_cl.main(npd, pd, td, clp)
  File "/home/gabriel/Github/asteca-project/ASteCA/packages/best_fit/best_fit_synth_cl.py", line 28, in main
    isoch_fit_params = pyabc_algor.main(
  File "/home/gabriel/Github/asteca-project/ASteCA/packages/best_fit/pyabc_algor.py", line 68, in main
    history = abc.run(
  File "/home/gabriel/miniconda3/envs/asteca/lib/python3.9/site-packages/pyabc/inference/smc.py", line 61, in wrapped_run
    ret = run(self, *args, **kwargs)
  File "/home/gabriel/miniconda3/envs/asteca/lib/python3.9/site-packages/pyabc/inference/smc.py", line 686, in run
    ret = self.run_generation(t=t)
  File "/home/gabriel/miniconda3/envs/asteca/lib/python3.9/site-packages/pyabc/inference/smc.py", line 815, in run_generation
    sample.normalize_weights()
  File "/home/gabriel/miniconda3/envs/asteca/lib/python3.9/site-packages/pyabc/population.py", line 417, in normalize_weights
    raise AssertionError("The total population weight is zero")
AssertionError: The total population weight is zero
```

**Comment by yannikschaelte** [comment]
Hm, the epsilon decay indicates that the distance calculation is overall working (in the sense that it at least calculates something non-trivial). Note you can also specify minimum consecutive epsilon difference to stop in such cases.

I am not sure whether the error is related. Could you share the model, distance, and prior? Also via mail if easier https://pyabc.readthedocs.io/en/latest/about.html.

**Comment by yannikschaelte** [comment]
It may also be useful here to inspect the history, e.g. via `h.get_distribution()` or `h.get_weighted_distances()`, to see whether e.g. all weights are zero in the last saved generation, or all distances the same, or all parameters or simulations equal https://pyabc.readthedocs.io/en/latest/api_datastore.html#pyabc.storage.History

**Comment by Gabriel-p** [comment]
> staying constant at a value != zero is however rather unusual

I can explain this. As a *distance* I'm using the (Bayesian) Poisson likelihood rate defined in [Tremmel et al. (2013; Eq. 10)](https://ui.adsabs.harvard.edu/abs/2013ApJ...766...19T/abstract). Since this is a likelihood it needs to be maximized. But pyABC needs to minimize distances, so what I do is invert the likelihood and add a constant to make this *distance* value positive. Something like this:

    dist = 500 - Likelihood

Hence, the `eps` value of ~260. The maximum likelihood is a priori unknown, which means that the constant I add needs to be large enough to make the distance positive. The downside of this is that the distance will no longer minimize to cero, it will minimize to some positive unknown value.

> Note you can also specify minimum consecutive epsilon difference to stop in such cases

I tried to use:

    history = abc.run(max_nr_populations=40, max_walltime=dt.timedelta(hours=0, minutes=5),min_eps_diff=0.001)

but I get:

    ABC.History INFO: Done <ABCSMC id=11, duration=0:01:21.779094, end_time=2021-12-17 15:54:47>
    *** TypeError: run() got an unexpected keyword argument 'min_eps_diff'

What am I doing wrong?

> I am not sure whether the error is related. Could you share the model, distance, and prior?

The model is rather large, it's a generator of synthetic stellar clusters. You can see it [here](https://github.com/asteca/ASteCA/blob/master/packages/synth_clust/synth_cluster.py) if you want to, but it basically returns a two-dimensional array of `N` points (stars in photometric space). The priors are uniform:

```
    prior = pyabc.Distribution(
        z=pyabc.RV("uniform", ranges[0][0], ranges[0][1] - ranges[0][0]),
        a=pyabc.RV("uniform", ranges[1][0], ranges[1][1] - ranges[1][0]),
        e=pyabc.RV("uniform", ranges[2][0], ranges[2][1] - ranges[2][0]),
        d=pyabc.RV("uniform", ranges[3][0], ranges[3][1] - ranges[3][0]),
        m=pyabc.RV("uniform", ranges[4][0], ranges[4][1] - ranges[4][0]),
        b=pyabc.RV("uniform", ranges[5][0], ranges[5][1] - ranges[5][0])
    )
```

(where `ranges` is a variable that holds the limits for each fitted parameter) and the distance was explained above.


> It may also be useful here to inspect the history, e.g. via `h.get_distribution()` or `h.get_weighted_distances()`

But in order to do this the run should finish successfully, right? Otherwise the `history` is not saved

**Comment by yannikschaelte** [comment]
> Hence, the `eps` value of ~260. The maximum likelihood is a priori unknown, which means that the constant I add needs to be large enough to make the distance positive. The downside of this is that the distance will no longer minimize to cero, it will minimize to some positive unknown value.

Ok, then this should be fine. Note that for likelihood-based formulations, you may want to check out https://pyabc.readthedocs.io/en/latest/examples/noise.html (which I would however not generally recommend, as it is often not efficient enough, such that an approximate solution may be preferable). If your model is fully deterministic (-> full likelihood known), other tools such as pyPESTO may be of interest.

> I tried to use:
> 
> ```
> history = abc.run(max_nr_populations=40, max_walltime=dt.timedelta(hours=0, minutes=5),min_eps_diff=0.001)
> ```
> 
> but I get:
> 
> ```
> ABC.History INFO: Done <ABCSMC id=11, duration=0:01:21.779094, end_time=2021-12-17 15:54:47>
> *** TypeError: run() got an unexpected keyword argument 'min_eps_diff'
> ```
> 
> What am I doing wrong?

This should have been introduced in pyABC 0.11.8.

> 
> > I am not sure whether the error is related. Could you share the model, distance, and prior?
> 
> The model is rather large, it's a generator of synthetic stellar clusters. You can see it [here](https://github.com/asteca/ASteCA/blob/master/packages/synth_clust/synth_cluster.py) if you want to, but it basically returns a two-dimensional array of `N` points (stars in photometric space). The priors are uniform:
> 
> ```
>     prior = pyabc.Distribution(
>         z=pyabc.RV("uniform", ranges[0][0], ranges[0][1] - ranges[0][0]),
>         a=pyabc.RV("uniform", ranges[1][0], ranges[1][1] - ranges[1][0]),
>         e=pyabc.RV("uniform", ranges[2][0], ranges[2][1] - ranges[2][0]),
>         d=pyabc.RV("uniform", ranges[3][0], ranges[3][1] - ranges[3][0]),
>         m=pyabc.RV("uniform", ranges[4][0], ranges[4][1] - ranges[4][0]),
>         b=pyabc.RV("uniform", ranges[5][0], ranges[5][1] - ranges[5][0])
>     )
> ```

Is it certain that `ranges[i][1] - ranges[i][0] > 0`?
> 
> (where `ranges` is a variable that holds the limits for each fitted parameter) and the distance was explained above.
> 
> > It may also be useful here to inspect the history, e.g. via `h.get_distribution()` or `h.get_weighted_distances()`
> 
> But in order to do this the run should finish successfully, right? Otherwise the `history` is not saved

The history is always saved and updated after each generation. in the file you specified as "sqlite:///..." and is returned by abc.new and abc.run, or can be accessed via `pyabc.History` afterwards.

**Comment by Gabriel-p** [comment]
> other tools such as pyPESTO may be of interest

I tried pyPESTO a few days ago, it's a great package! Although I get reasonable results, I get very low ESS (~10) using as a sampler:

    sampler = sample.AdaptiveParallelTemperingSampler(
        internal_sampler=sample.AdaptiveMetropolisSampler(), n_chains=20)
    result = sample.sample(problem, 1.5e4, sampler, x0=init_model)

So I think pyABC is a better tool for my problem.


> This should have been introduced in pyABC 0.11.8

Indeed, I upgraded the package and I can use it now.



> Is it certain that `ranges[i][1] - ranges[i][0] > 0`?

Yep.



> The history is always saved and updated after each generation. in the file you specified as "sqlite:///..."

Found the file thank you. I'll try to reproduce the error and come back with more info.


Could you point me to some literature to understand more about how this algorithm works please? I'm having trouble understanding concepts like the ESS (if there's no autocorrelation time, why is there an ESS? or maybe there is an autocorr time?), or how many samples are actually in a population (is it the number of particles I fixed? is it the total number of particles that were sampled until the fixed number below the threshold was achieved?)

**Comment by yannikschaelte** [comment]
Great! Btw that history you can also always use to use a result until you canceled run, or something went wrong. Yet here something fundamental seems to go wrong, such that one should investigate, as you said.

Regarding literature, maybe e.g. this [presentation](https://yannikschaelte.github.io/pres_ose2020) may help. For core algorithms, we provide [links](https://pyabc.readthedocs.io/en/latest/api_inference.html#tonistumpf) to the literature (e.g. this one describes the basic ABC-SMC algorithm). If you are interested in a more thorough introduction into ABC methods, there is a "Handbook of ABC", most chapters of which are openly available via preprints. Further, this earlier paper by [Beaumont](https://www.math.kth.se/matstat/gru/sf2935/annurev-ecolsys.pdf) gives a nice overview.

Regarding the ESS in particular: These weights arise from the (sequential) importance sampling we perform, to more efficiently focus on high-density regions, instead of sampling from the prior. It is a different ESS than in MCMC -- there, it accounts for autocorrelation, while here all samples are independent and it accounts for the difference in sampling distribution (see any literature on importance sampling).

The population size is fixed to whatever n you define in ABCSMC (there are also [adaptive approaches](https://pyabc.readthedocs.io/en/latest/api_populationstrategy.html#pyabc.populationstrategy.AdaptivePopulationSize), which may be beneficial, but can also lead to unreasonably large population sizes, thus recommending to always set an upper bound when using those). In a generation, n_sample candidate particles are sampled until n have been accepted, with typically n_sample --> inf for t --> inf and epsilon --> 0.

**Comment by yannikschaelte** [comment]
Regarding use of pyPESTO, the ESS can be increased by increasing the chain length. In most of our applications, less parallel chains suffices (3-10?). However, it currently only implements/interfaces MCMC methods, which do not parallelize as well as SMC (but often perform well in likelihood-based inference). If you want the full customization of an established likelihood-based sampler, you may want to try also directly using STAN, PYMC3, or EMCEE (or the latter two interfaced via pyPESTO). But certainly, in some cases ABC may be just better.

**Comment by Gabriel-p** [comment]
Thank you very much for the literature Yannik! I'll take a look at it as soon as I can.

I used pyPESTO with:

    sampler = sample.AdaptiveParallelTemperingSampler(
        internal_sampler=sample.AdaptiveMetropolisSampler(), n_chains=20)

and it did give reasonable results, but with rather poor ESS as I stated. I've already tried `emcee` and I could not find a setting that works for my model (the chains get stuck and never explore the parameters space). What I'm currently using is [ptemcee](https://github.com/willvousden/ptemcee) which works great but I need a running time of at least 30 min for reasonable results. I was hoping pyABC would help me cut back on that a little bit. Also, given the nature of my model (i.e., no analytic expression but a "black box" that generates synthetic data) ABC seems to be the proper approach.

I'll look a bit more into this issue probably after the holiday season.

Cheers!

**Comment by yannikschaelte** [comment]
Closing due to inactivity. Feel free to reopen if the issue persists!
